//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;

    public partial class User
    {
        public int userID { get; set; }
        public string userName { get; set; }

        //[Required]
        [StringLength(30)]
 
        public string userPass { get; set; }


        public Nullable<int> role { get; set; }
    }
}
